import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./Nav";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Article",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
          <div className="nav">
            <Nav />
          </div>
        </div>
        <div className="outlink">
          {children}
        </div>
      </body>
    </html >
  );
}
