import { Inter } from "next/font/google";
import "./globals.css";
import SideNav from "./SideNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Article",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="side-nav">
          <SideNav />
        </div>
        <div className="outlink">
          {children}
        </div>
      </body>
    </html>
  );
}
